### ISSUE TITLE
Check parameter prior columns during validation

### ISSUE THREAD

**Issue by dweindl** [PEtab-dev/PEtab#131]
`petab.lint.problem` does not check parameter prior columns yet (#130). This should be updated:

- [x] Ensure a valid prior type is chosen
- [x] Valid prior distribution parameters are provided

**Comment by dweindl** [comment]
@yannikschaelte : First point is done, right? Can you take care of the second point? Then the prior part is done...

**Comment by yannikschaelte** [comment]
yes, part one is done. part two entails making a list of argument sizes (number of `;`) of the different prior models. will do that.

**Comment by yannikschaelte** [comment]
parameters are checked since 0.1.4.
