### ISSUE TITLE
Visualization: add checks for optional columns 

### ISSUE THREAD

**Issue by erikadudki** [PEtab-dev/PEtab#165]
Currently, I think most columns in e.g. measurement files (e.g. observableParameters) are required for the plotting routine. 
Would be good to add some tests in the beginning, to check if the optional columns (e.g."preequilibrationConditionId","observableParameters", "noiseParameters") exist.

**Comment by MerktSimon** [comment]
Also in the visualization specification file some of the optional columns seem not to be optional in fact (e.g. "xValues").

**Comment by MerktSimon** [comment]
Is there a generally good way to deal with this? Try-except as was used for conditionName in #142 or check them all in the beginning? The first way decreased coverage by 0.1%..

**Comment by yannikschaelte** [comment]
I am not completely sure why e.g. observableParameters are necessary for the visualization?

But regardless: In general, it may be a good idea to "normalize" the dataframes at the beginning always, i.e. to append empty columns. then these can always be assumed to exist (though the values being empty must still be handled correctly). Alternatively, one can always do a ``if "something" in df.columns`` check. Not sure what is better.

Coverage decrease you can ignore, or add tests with the column present, and the column not present, to check if everything works.
