### ISSUE TITLE
Cleanup PEtab documentation: Extension vs Optional fields

### ISSUE THREAD

**Issue by dweindl** [PEtab-dev/PEtab#184]
I think "extensions" should rather be removed and moved to the tool interpreting those things. If kept here, they should be well defined and listed as "optional" (e.g. remove `hierarchicalOptimization`).

**Comment by yannikschaelte** [comment]
do you mean removing the column entirely? or just the documentation?
I think it makes sense to keep stuff like "hierarchicalOptimization" in here, even if just one tool currently supports it, because that allows to keep all info in one place.

**Comment by dweindl** [comment]
Remove or explain in detail and mark as optional.

**Comment by yannikschaelte** [comment]
I would then currently suggest to label it as optional, and in the docs describe it (pot. with link to paper or supporting tool, but none yet to be honest).
In general, it may happen that people add own optional columns, which then won't be documented in petab right away, and at some point might become standard.

**Comment by dweindl** [comment]
From discussion with @LeonardSchmiester and @yannikschaelte:

- [ ] Remove "extensions". This is something that should be mentioned for any tools supporting PEtab (e.g. "hierarchicalOptimization")
- [ ] Prior columns in parameter table: `priorType` and `priorParameters` should be removed in favor of  `initializationPriorType`, `initializationPriorParameters`, `objectivePriorType`, and `objectivePriorParameters`. They should to into the main section, not as "additional columns"

**Comment by yannikschaelte** [comment]
done via #311
