### ISSUE TITLE
Visualization: log yScale has no effect

### ISSUE THREAD

**Issue by MerktSimon** [PEtab-dev/PEtab#197]
If you chose log or log10 in the field `yScale` in the visualization file it has no effect on the plot.
Example Isensee:
![Figure_2](https://user-images.githubusercontent.com/49190262/70948304-711c1500-205b-11ea-8bd7-1da665a26dce.png)

plotId | plotName | plotTypeSimulation | plotTypeData | datasetId | xValues | xOffset | xLabel | yValues | yOffset | yLabel | legendEntry | xScale | yScale
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
plot1 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__4_ABnOH_and_ctrl | fourABnOH_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | 4-ABnOH/Ctrl | lin | lin
plot1 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__4_ABnOH_and_Fsk | fourABnOH_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | 4-ABnOH/Fsk(10) | lin | lin
plot1 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp_cAMPS_pAB_and_ctrl | Rp_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp-cAMPS-pAB/Ctrl | lin | lin
plot1 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp_cAMPS_pAB_and_ctrl | Rp_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp-cAMPS-pAB/Fsk(10) | lin | lin
plot1 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp8_Br_cAMPS_pAB_and_ctrl | Rp8_Br_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp8-Br-cAMPS-pAB/Ctrl | lin | lin
plot1 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp8_Br_cAMPS_pAB_and_Fsk | Rp8_Br_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp8-Br-cAMPS-pAB/Fsk(10) | lin | lin
plot1 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp8_pCPT_cAMPS_pAB_and_ctrl | Rp8_pCPT_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp8-pCPT-cAMPS-pAB/Ctrl | lin | lin
plot1 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp8_pCPT_cAMPS_pAB_and_Fsk | Rp8_pCPT_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp8-pCPT-cAMPS-pAB/Fsk(10) | lin | lin
plot7 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__4_ABnOH_and_ctrl | fourABnOH_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | 4-ABnOH/Ctrl | lin | log
plot7 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__4_ABnOH_and_Fsk | fourABnOH_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | 4-ABnOH/Fsk(10) | lin | log
plot7 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp_cAMPS_pAB_and_ctrl | Rp_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp-cAMPS-pAB/Ctrl | lin | log
plot7 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp_cAMPS_pAB_and_ctrl | Rp_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp-cAMPS-pAB/Fsk(10) | lin | log
plot7 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp8_Br_cAMPS_pAB_and_ctrl | Rp8_Br_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp8-Br-cAMPS-pAB/Ctrl | lin | log
plot7 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp8_Br_cAMPS_pAB_and_Fsk | Rp8_Br_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp8-Br-cAMPS-pAB/Fsk(10) | lin | log
plot7 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp8_pCPT_cAMPS_pAB_and_ctrl | Rp8_pCPT_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp8-pCPT-cAMPS-pAB/Ctrl | lin | log
plot7 | JI09_150302_Drg345_343_CycNuc | LinePlot | MeanAndSD | JI09_150302_Drg345_343_CycNuc__Rp8_pCPT_cAMPS_pAB_and_Fsk | Rp8_pCPT_cAMPS_pAB_incubation_time | 0 | Incubation Time [min] | pRII_Microscopy | 0 | pRII_Microscopy | Rp8-pCPT-cAMPS-pAB/Fsk(10) | lin | log

**Comment by MerktSimon** [comment]
xScale is implemented actually.
It can do "linear", "log(10)" and "order".
Contrary to the data format documentation where "order" does not appear at all, there is no difference between "log" and "log10". The former does nothing and the latter results in the `set_xscale("log").

**Comment by MerktSimon** [comment]
we should agree on what log or log10 implies and which bases we want to use. Then I will implement this analogously for yscale

**Comment by yannikschaelte** [comment]
> xScale is implemented actually.
> It can do "linear", "log(10)" and "order".
> Contrary to the data format documentation where "order" does not appear at all, there is no difference between "log" and "log10". The former does nothing and the latter results in the `set_xscale("log").

but is that also handled correctly in the routine? I think I had log and log10 giving the same plots, but not sure right now.

**Comment by yannikschaelte** [comment]
log would be to the basis e, and log10 for the basis 10, scaling the axis accordingly. those are the bases we allow for scaling in petab throughout.
