### ISSUE TITLE
Fix: Circling lineplots in case of unsorted xValues in dose-response plot

### ISSUE THREAD

**Issue by MerktSimon** [PEtab-dev/PEtab#207]
![Figure_2](https://user-images.githubusercontent.com/49190262/71919504-233f8c00-3185-11ea-8e46-1f62edef9689.png)

**Comment by JanHasenauer** [comment]
- please implement an automatic sorting of the x-values
- if an x-value appears more than once, I would suggest that the mean is computed and shown on addition to the individual samples. the line should than connect the mean and not the individual points.

**Comment by erikadudki** [comment]
@MerktSimon: does the implementation of sorting the x-values in #396 solve this issue?

**Comment by MerktSimon** [comment]
yes
