### ISSUE TITLE
Values of xScale

### ISSUE THREAD

**Issue by yannikschaelte** [PEtab-dev/PEtab#232]
In the docs, lin, log, log10 are permitted, but plotting_options.py also checks for 'order'.

**Comment by JanHasenauer** [comment]
@MerktSimon @yannikschaelte 
The doc seems to mention now also 'order'. 
Can this issue be closed?

**Comment by yannikschaelte** [comment]
If it's in master already, it would seem fine to close.

**Comment by plakrisenko** [comment]
fixed in #372
