### ISSUE TITLE
Check datasetID of simulatedData during visualization

### ISSUE THREAD

**Issue by MerktSimon** [PEtab-dev/PEtab#239]
Currently for plotting simulated data the visualization routine just takes the values of the simulatedData file which are at the same position as in the measurement file. While imo this is a good enough guess, I think the routine should at least check that datasetID (if existing) and conditionID are consistent with the measurement file and throw an error or warning if this is not true.
What do you think?

**Comment by dweindl** [comment]
Yes, the current mapping sounds insufficient and is pretty much asking for trouble. You check as much as possible to ensure proper mapping. Where this is not possible, it should be clearly documented that identical ordering is expected.
