### ISSUE TITLE
More flexible handling of {observable,noise}Parameters?

### ISSUE THREAD

**Issue by dweindl** [PEtab-dev/PEtab#242]
New issue to disentangle the discussions in #201:

_Originally posted by @yannikschaelte in https://github.com/ICB-DCM/PEtab/issues/201#issuecomment-577139153_

Remains to decide on the additional naming conventions on observable and noise parameters. Suggestion of @dweindl :

> You mean {observable,noise}Parameter${n}_${observableId}? Right. Not too happy about them either. Not because of potential name collisions, but mostly because they make it pretty hard to read the measurement table in case of multiple parameters. Literally every time, I am wondering which parameter was parameter1 and which one was parameter2. This could be addressed by explicitly stating the observable parameter to override in the {observable|noise}Parameters columns (e.g. offset:400;scaling:2.5). This way, it would be more intuitive and we could get rid of the remaining reserved / imposed names. Downside is, that it doesn't increase readability in case there is only one parameter (although then the prefix could be made optional).

As an extension, one could also add additional columns ``observableParameters`` and ``noiseParameters`` to the observable file, having as content e.g. ``scaling;offset``. This would allow to in the measurement file not have to write ``scaling:2.5;offset:400``, but still allow the previous short form ``2.5;400``, with the order specified by the column in the observable file. This is similar to named arguments in python. In that approach, one would have thus the possibility to write both forms in the measurement file, at the cost of one additional parsing step.

**Comment by JanHasenauer** [comment]
No preference from my side.

**Comment by dweindl** [comment]
Closing due to lack of interest.
