### ISSUE TITLE
Can noiseFormula be optional?

### ISSUE THREAD

**Issue by dweindl** [PEtab-dev/PEtab#259]
... and if not provided, we assume sigma=1.0? Would be more convenient in some cases. (e.g. copasi export)

**Comment by yannikschaelte** [comment]
sounds reasonable. dangerous, but the de-facto standard.

**Comment by JanHasenauer** [comment]
sigma = 1 and additive normal measurement noise is a good default. this would mean that we use least square

**Comment by JanHasenauer** [comment]
- [ ] specify in documentation
- [ ] add a test case

**Comment by dweindl** [comment]
This was discussed during a recent PEtab editor meeting. It's preferable to be explicit, so `noiseFormula` always has to be set.
