### ISSUE TITLE
column 'xValues' in visualization file should be mandatory ?

### ISSUE THREAD

**Issue by erikadudki** [PEtab-dev/PEtab#283]
For the visualization routine the column 'xValues' is still mandatory, since it defines how the data should be plotted (e.g. time series or dose response).
Is that okay for everyone? 

- If yes, we should change it in the documentation. 
- If not, we should then agree on a default case to plot, if xValues is not provided.

**Comment by yannikschaelte** [comment]
I think xValues="time" might make a reasonable default (time-resolved data being more common than dose-response?). It is actually mentioned as default in the docs, however only in the text, not in the head of the entry ...

**Comment by LeonardSchmiester** [comment]
Could one theoretically infer it from the data structure, if its time or dose resolved?

Otherwise, I think time as default or making it mandatory is both fine. As dose-response is also quit common, maybe it's better to just make it mandatory :thinking:

**Comment by yannikschaelte** [comment]
inferring could be fun. how could one do that? check for multiple instances of time? apart, also both fine for me if dose-response is common too.

**Comment by plakrisenko** [comment]
I think we agreed on making "time" default for now and making xValues optional

**Comment by JanHasenauer** [comment]
@erikadudki Has this been addressed? if yes, please close.

**Comment by erikadudki** [comment]
hasn't been addressed yet, for me it is still not clear, which way to go. It sounds like both is fine :) 
but from the last statement: should we go for 'time' as default for xValues?

**Comment by JanHasenauer** [comment]
yes, let's go for time as a default.
if there is only one time point for the complete datasetID, the default should ideally be switched to dose-response.

**Comment by erikadudki** [comment]
in the case of only one time point, and dose-response should be plotted, then the question arises which condition should be plotted, if there exist more than one in the exp-condition-file? 

- The first one, with a warning something like: 'First dose-response condition is plotted. Check which condition you want to plot and possibly enter it into the column xValues in the visualization table.' ?

- (or all of them - but this then depends on the number of defined plotIds in the visu-table, how many were defined, how many conditions are defined, etc..... I would say this is not covenient? )

**Comment by JanHasenauer** [comment]
If there is more than one condition in the condition table, one could check which parameters actually change. If only one parameter changes, this is what should be shown on the x-axis. if multiple parameters change, I would simply "order" the x-axis. (unless somebody has a better suggestion)

**Comment by erikadudki** [comment]
@JanHasenauer What do you mean by 'order' the x-axis? 
For me, the case if multiple parameters change, is not trivial. If there are multiple parameters that change, they probably belong to different datasets and have different conditionIDs. One has to track down which condition belongs to which dataset.
One possibility to do that, would be to find via the conditionID the respective datasetId from the measurement file, but then the 'datasetId' would be mandatory, which is not...
In my opinion, this case is a special handling and should inform the user to just use the xValues- column in the visu table to specify which conditions should be plotted :)

**Comment by JanHasenauer** [comment]
> @JanHasenauer What do you mean by 'order' the x-axis?
With "order", I was referring referring to the type of x-scale (see https://petab.readthedocs.io/en/latest/documentation_data_format.html#visualization-table)

> If there are multiple parameters that change, they probably belong to different datasets and have different conditionIDs.
Yes. Indeed, dose response curves require always multiple conditions. I was imaging a plot and labelling like in Subplot B and C here: https://journals.plos.org/ploscompbiol/article/file?type=supplementary&id=info:doi/10.1371/journal.pcbi.1007147.s005
