### ISSUE TITLE
should observableId be restricted to the SBML Id syntax?

### ISSUE THREAD

**Issue by fbergmann** [PEtab-dev/PEtab#291]
Still slowly going through the models, and i found a new issue with the blasi model, there the observable table specifies: 

```
observableId	observableName	observableFormula	noiseFormula	observableTransformation	noiseDistribution
0ac		x_0ac	noiseParameter1_0ac	log	normal
4ac		x_4ac	noiseParameter1_4ac	log	normal
k12		x_k12	noiseParameter1_k12	log	normal

```

the issue here is that `0ac` and `4ac` are not valid SBML ids (as those are not allowed to start with a number). The documentation is unclear about it, but i think this needs to be stated explicitly.

**Comment by fbergmann** [comment]
ideally this would be tested by petablint, which you could easily do using libsbml, just calling: 

`
import libsbml
True
>>> libsbml.SyntaxChecker_isValidSBMLSId('ac')
True
>>> libsbml.SyntaxChecker_isValidSBMLSId('0ac')
False
>>> libsbml.SyntaxChecker_isValidSBMLSId('_0ac')
True
```

**Comment by dweindl** [comment]
You are right, should be added to the docs. For some IDs it is checked already, but not for all.

**Comment by LeonardSchmiester** [comment]
Observable Ids in Blasi should be valid now
