### ISSUE TITLE
DataFrame parameter requires the columns {'nominalValue'}.

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#303]
If I specify estimate==1 for all parameters, why do I still have to provide the `nominalValue` column, given that its optional (see https://petab.readthedocs.io/en/stable/documentation_data_format.html#parameter-table). What should I pass if I don't want to specify any value? `np.nan`, `''`?

**Comment by dweindl** [comment]
Sounds like a bug to me.
