### ISSUE TITLE
Unclear Documentation of noiseFormula

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#304]
Documentation of noiseFormula specified that its possible to specify numerical values here (conflicting with the type declaration as string), which doesn't seem to work (passing numerical values throws a mildly uninformative `TypeError: expected string or bytes-like object` error.)

Seems to be related to #264, but there is an issue with documentation nevertheless.

**Comment by dweindl** [comment]
Okay, 'string' in this case also included e.g. '1.0'. But should be clarified. Type error should not have occured.

**Comment by FFroehlich** [comment]
Okay after fixing other parts of the petab specification I no longer get TyperErrors and both numerical and string variables seem to work. Documenation may still need clarification though.
