### ISSUE TITLE
observableParameters not optional in measurements table?

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#305]
https://petab.readthedocs.io/en/stable/documentation_data_format.html#measurement-table claims observableParameters is option, but https://github.com/PEtab-dev/PEtab/blob/master/petab/measurements.py#L322 doesn't seem to agree with that.

**Comment by FFroehlich** [comment]
same goes for noiseParameters.

**Comment by yannikschaelte** [comment]
true, seems like we should check for existence

**Comment by dweindl** [comment]
See also #325, where `measurements.assert_overrides_match_parameter_count` assumes observable and noise parameter columns exist.

**Comment by dweindl** [comment]
Should be addressed by #350
