### ISSUE TITLE
Allow definition of multiple parameter definition files

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#307]
Motivation:
It is possible to include multiple condition files which may define local parameter assignments. However, you can't assemble the parameter table from multiple files, which means you have to create individual parameter tables and somewhat impede the modularity of being able to assemble condition files arbitrarily.

Proposed Solution:
Allow composition of parameter tables from multiple files. Throw errors upon duplicate definition of parameters.

**Comment by dweindl** [comment]
Sounds reasonable to me. Any other opinions?

**Comment by yannikschaelte** [comment]
what if there is a parameter shared between all conditions? Likely to happen if it is the same underlying model. Then that needs to be defined for all ...

**Comment by FFroehlich** [comment]
As far as I understood there doesnt have to be a 1-1 mapping between parameter files and conditions. All common parameters could go in one file and all the conditions specific ones in another

**Comment by dweindl** [comment]
Something like SBML LocalParameters? could do... everything lives in a separate namespace, unless defined in a global parameter table?

**Comment by yannikschaelte** [comment]
> As far as I understood there doesnt have to be a 1-1 mapping between parameter files and conditions. All common parameters could go in one file and all the conditions specific ones in another

then one would need to be major pam file? -> list structure does not apply. but currently we have one outer pam file, which could easily be combined with an optional inner list of pam files.

pam = parameter

**Comment by FFroehlich** [comment]
I don't understand either of your comment. Not sure we are talking about the same thing.

For example I currently have the following parameter table:

parameterId | parameterScale | lowerBound | upperBound | estimate | nominalValue
-- | -- | -- | -- | -- | --
kG1S | log10 | 1E-05 | 10.0 | TRUE |  
kSG2 | log10 | 1E-05 | 10.0 | TRUE |  
kG2MG1 | log10 | 1E-05 | 10.0 | TRUE |  
kphi | log10 | 1E-05 | 10.0 | TRUE |  
kwash | log10 | 1E-05 | 10.0 | TRUE |  
G1_0 | log10 | 1.0 | 10000.0 | TRUE |  
S_0 | log10 | 1.0 | 10000.0 | TRUE |  
G2_0 | log10 | 1.0 | 10000.0 | TRUE |  
D_0 | log10 | 1.0 | 10000.0 | TRUE |  
YKL-5-124__-0_5_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-0_5_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-0_5_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-0_5_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_0_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_0_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_0_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_0_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_5_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_5_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_5_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_5_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_0_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_0_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_0_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_0_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_5_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_5_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_5_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_5_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-3_0_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-3_0_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-3_0_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-3_0_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_0_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_0_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_0_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_0_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_5_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_5_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_5_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_5_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__1_0_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__1_0_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__1_0_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__1_0_rphi | log10 | 0.001 | 1000.0 | TRUE |  
lambda_reg | log10 | 0.001 | 1000.0 | FALSE | 0.1

I have 4 models, 77 drugs, 62 cell lines, and 7 different values for lambda_reg. This yields a total of 133672 parameter files that I have to generate, and the number of models and lambda_reg values may easily change. I don't want to use all data at once since drug/cell-line pairs are currently assumed to be independent.

I would like to split these files into 

a shared parameter definition

parameterId | parameterScale | lowerBound | upperBound | estimate | nominalValue
-- | -- | -- | -- | -- | --
kG1S | log10 | 1E-05 | 10.0 | TRUE |  
kSG2 | log10 | 1E-05 | 10.0 | TRUE |  
kG2MG1 | log10 | 1E-05 | 10.0 | TRUE |  
kphi | log10 | 1E-05 | 10.0 | TRUE |  
G1_0 | log10 | 1.0 | 10000.0 | TRUE |  
S_0 | log10 | 1.0 | 10000.0 | TRUE |  
G2_0 | log10 | 1.0 | 10000.0 | TRUE |  
D_0 | log10 | 1.0 | 10000.0 | TRUE |  

a shared parameter definition that is only included for 2 out of the 4 models

parameterId | parameterScale | lowerBound | upperBound | estimate | nominalValue
-- | -- | -- | -- | -- | --
kwash | log10 | 1E-05 | 10.0 | TRUE |  

a regularization parameter definition that can be included ad hoc.

parameterId | parameterScale | lowerBound | upperBound | estimate | nominalValue
-- | -- | -- | -- | -- | --
lambda_reg | log10 | 0.001 | 1000.0 | FALSE | 0.1

a drug specific parameter which defines bounds for the mapped parameters

YKL-5-124__-0_5_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-0_5_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-0_5_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-0_5_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_0_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_0_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_0_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_0_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_5_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_5_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_5_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-1_5_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_0_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_0_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_0_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_0_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_5_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_5_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_5_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-2_5_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-3_0_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-3_0_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-3_0_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__-3_0_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_0_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_0_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_0_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_0_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_5_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_5_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_5_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__0_5_rphi | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__1_0_rG1S | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__1_0_rG2MG1 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__1_0_rSG2 | log10 | 0.001 | 1000.0 | TRUE |  
YKL-5-124__1_0_rphi | log10 | 0.001 | 1000.0 | TRUE | 

That would be a total of 86 files, where I would then specify the way these files are combined in individual yaml files (I would still need the same high number of yaml files, but those are way easier to generate)

**Comment by dweindl** [comment]
Yeah, seems like I had a different understand of "common parameters". I thought you meant different models with overlapping parameter IDs, but where only some of those really have the same meaning.

So yes, for the case where we have only one global parameter namespace, it is rather easy to split definitions across different files and treat redundant (or only contradictory?) parameter definitions as errors.
