### ISSUE TITLE
Include PEtab version in tables

### ISSUE THREAD

**Issue by dweindl** [PEtab-dev/PEtab#309]
As discussed yesterday, it might be helpful to encode the format version in all files.

@fbergmann suggested a separate header-only column. 

Shall we go for `petabVersion:${version}`? 

Required updates:
- [ ] documentation
- [ ] handling in validator: header in condition table does not have to match ID-schema
- [ ] handling in parameter mapping: ignore that column of the condition table
- for all other tables, this is just an additional column which is ignored anyways
- [ ] I guess, that would demand raising the format version number

**Comment by LeonardSchmiester** [comment]
> Shall we go for petabVersion:${version}?

Fine for me

**Comment by dweindl** [comment]
As of https://github.com/PEtab-dev/PEtab/pull/537, yaml files containing the PEtab version are mandatory. Therefore, I'd say this is obsolete.
