### ISSUE TITLE
Show logo on pypi

### ISSUE THREAD

**Issue by yannikschaelte** [PEtab-dev/PEtab#312]
The old game: Use absolute URLS for images to appear on pypi.

**Comment by dweindl** [comment]
We could replace them automatically when reading the readme in `setup.py`. Then things would work both on pypi and locally offline.

**Comment by dweindl** [comment]
Reminds me of #89 ;)

**Comment by yannikschaelte** [comment]
old one ;) yes, makes sense. closing in favor of that one
