### ISSUE TITLE
Link to example models in readme

### ISSUE THREAD

**Issue by paulflang** [PEtab-dev/PEtab#315]
I was wondering if you could change the link to example models in the readme to 'https://github.com/LeonardSchmiester/Benchmark-Models/tree/hackathon/hackathon_contributions_new_data_format' or provide a more detailed description? Otherwise the examples are a bit hard to find, cause the corresponding folder only reads as 'hackathon_contributions_new_data_...' at first.

**Comment by dweindl** [comment]
Hi Paul, thanks for reporting. Fully agreeing. Fixed in #316 .

**Comment by paulflang** [comment]
Thanks.
