### ISSUE TITLE
samples in PEtab documentation

### ISSUE THREAD

**Issue by thomassligon** [PEtab-dev/PEtab#318]
[https://github.com/PEtab-dev/PEtab/blob/master/doc/documentation_data_format.md](https://github.com/PEtab-dev/PEtab/blob/master/doc/documentation_data_format.md)

It would be very good to have samples in this document.
Condition table has no samples.
Observable table has a row labeled “e.g.”.
I suggest adding a very small table, including the header row, but only a few rows and columns, perhaps taken from the benchmark collection, to all descriptions.

**Comment by yannikschaelte** [comment]
Hi Tom, this should have been addressed in #378. Giving useful examples for all tables is difficult, but now it should become clearer what is meant. For examples, I recommend having a look at the models in https://github.com/Benchmarking-Initiative/Benchmark-Models-PEtab/tree/master/Benchmark-Models. Hope that helps!
