### ISSUE TITLE
visualize.plot_data_and_simulation fails if preequilibrationConditionId is not provided

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#320]
`preequilibrationConditionId` should be optional, but looks like `plot_data_and_simulation` expects it: 

https://github.com/PEtab-dev/PEtab/blob/8b03c8f20c8042c5375adabfe23bab19c3a649b0/petab/visualize/helper_functions.py#L471

**Comment by dweindl** [comment]
@erikadudki : is that already addressed in #282?

**Comment by erikadudki** [comment]
yes, is addressed in #282
