### ISSUE TITLE
`rdatas_to_measurement_df` and `get_data_to_plot` are incompatible

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#324]
`petab.visualize.get_data_to_plot` expects simulation data in `simulation` field, but `pypesto.PetabImporter.rdatas_to_measurement_df` writes it to `measurement`. Might be due to checking out too many toolboxes from development branches, but given that the petab importer in pypesto copies from the measurement_df.

**Comment by yannikschaelte** [comment]
true, that has not been adapted yet. We recently decided to in the simulation tables call the values no longer "measurement" but "simulation", this is missing in amici/pypesto yet.

**Comment by MerktSimon** [comment]
for AMICI see https://github.com/ICB-DCM/AMICI/issues/971

**Comment by dweindl** [comment]
Closing here, as this rather needs fixing in AMICI/pyPESTO than in PEtab. See issue above.
