### ISSUE TITLE
Specifying parameters that should be fit to conditions individually

### ISSUE THREAD

**Issue by paulflang** [PEtab-dev/PEtab#325]
My understanding is that PEtab (and AMICI) supports two kind of parameters:
- parameters that are not subject to optimisation in any of the conditions (specified in the Conditions table)
- parameters are subject to optimisation across all conditions, such that they have the same value for all conditions.

I was now wondering how to specify a third kind of parameters:
- parameters that are subject to optimisation, but may have different values for different conditions.

This problem comes up when states have non-observed initial conditions that need to be fit by the parameter fitting algorithm, but the initial conditions may vary across different perturbation experiments. In particular I think of cell cycle time courses under different perturbations.

**Comment by FFroehlich** [comment]
It is supported, but I agree that the wording in the documentation is odd and could need some rework. The `${parameterOrStateOrCompartmentId1}` field in the condition table allows you to implement local, condition specific parameter overrides. The respective local parameter have to be defined in the parameter table though.

**Comment by paulflang** [comment]
Thanks you very much. I tried to specify a simple model containing the aforementioned three types of parameters as you suggested (see .tsv and .xml files here: [RP_v1.1.zip](https://github.com/PEtab-dev/PEtab/files/4238262/RP_v1.1.zip)):

1. I put all parameters that are not subject to optimisation in any of the conditions (case I) into the `Conditions table`, using their IDs as column name and values as entries. I made sure these parameters do not appear in the `Parameter table`.
2. I put parameters that are subject to optimisation across all conditions (case II) in the `Parameters table` but not the `Conditions table`. I assume they would be fitted such that their value is identical across all conditions, as I did not specify them in the `Conditions table`. Is this correct?
3. I put parameters that are subject to optimisation, but may have different values for different conditions (case III) in the `Conditions table` and `Parameter table`. I prefixed their ID with 'condSpecific_' to be used as `Conditions table` column name. The column entries correspond to the respective parameter ID. I made sure that these parameter IDs also appear in the `Paramteter table` with `estimate` set to `1`. I assume that these parameters would be fitted for each condition individually, as they do also appear in the `Conditions table`. Is this correct?

Unfortunately, petablint identified the following problem with my specification:
```
(base) paul@paul-VirtualBox:/media/sf_DPhil_Project/Project07_Parameter Fitting/PEtab/examples/RP_v1.1$ petablint -y RP_v1.1.yaml 
Traceback (most recent call last):
  File "/home/paul/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4411, in get_value
    return libindex.get_value_at(s, key)
  File "pandas/_libs/index.pyx", line 44, in pandas._libs.index.get_value_at
  File "pandas/_libs/index.pyx", line 45, in pandas._libs.index.get_value_at
  File "pandas/_libs/util.pxd", line 98, in pandas._libs.util.get_value_at
  File "pandas/_libs/util.pxd", line 83, in pandas._libs.util.validate_indexer
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/paul/anaconda3/bin/petablint", line 11, in <module>
    load_entry_point('petab', 'console_scripts', 'petablint')()
  File "/media/sf_DPhil_Project/Project07_Parameter Fitting/PEtab/petab/petablint.py", line 159, in main
    ret = petab.lint.lint_problem(problem)
  File "/media/sf_DPhil_Project/Project07_Parameter Fitting/PEtab/petab/lint.py", line 611, in lint_problem
    check_measurement_df(problem.measurement_df, problem.observable_df)
  File "/media/sf_DPhil_Project/Project07_Parameter Fitting/PEtab/petab/lint.py", line 135, in check_measurement_df
    df, observable_df)
  File "/media/sf_DPhil_Project/Project07_Parameter Fitting/PEtab/petab/measurements.py", line 332, in assert_overrides_match_parameter_count
    split_parameter_replacement_list(row[OBSERVABLE_PARAMETERS]))
  File "/home/paul/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 871, in __getitem__
    result = self.index.get_value(self, key)
  File "/home/paul/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4419, in get_value
    raise e1
  File "/home/paul/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 4405, in get_value
    return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
  File "pandas/_libs/index.pyx", line 80, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 90, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1618, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1626, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'observableParameters'
(base) paul@paul-VirtualBox:/media/sf_DPhil_Project/Project07_Parameter Fitting/PEtab/examples/RP_v1.1$ 
```

I do not know why petablint seems to expect `observableParameters`. Do you have an idea what is wrong with my model specification?

**Comment by dweindl** [comment]
Hi @paulflang , this is a bug in `petablint`. Those fields should be optional, but are not correctly created as such. Needs fixing. As quick workaround, you can simple add two empty columns `observableParameters` and `noiseParameters` to your measurement table.

Then you should get the following output:

```
Condition table contains column for unknown entity 'icD'. Column names must match parameter, species or compartment IDs specified in the SBML model.
Observable ID ab_E2f shadows model entity.
Observable ID ab_Ce shadows model entity.
Observable ID ab_pRb shadows model entity.
Bounds for log10 scaled parameter icE2f must be positive.
```

>     1. I put all parameters that are not subject to optimisation in any of the conditions (case I) into the `Conditions table`, using their IDs as column name and values as entries. I made sure these parameters do not appear in the `Parameter table`.

Sounds good. Petablint will complain, because you specified a column `icD` that is not referenced  anywhere. 

>     2. I put parameters that are subject to optimisation across all conditions (case II) in the `Parameters table` but not the `Conditions table`. I assume they would be fitted such that their value is identical across all conditions, as I did not specify them in the `Conditions table`. Is this correct?

Correct.

>     3. I put parameters that are subject to optimisation, but may have different values for different conditions (case III) in the `Conditions table` and `Parameter table`. I prefixed their ID with 'condSpecific_' to be used as `Conditions table` column name. The column entries correspond to the respective parameter ID. I made sure that these parameter IDs also appear in the `Paramteter table` with `estimate` set to `1`. I assume that these parameters would be fitted for each condition individually, as they do also appear in the `Conditions table`. Is this correct?

Partially correct. For those condition-specific parameters, the column name would be parameter ID as defined in the model, say "p1". The value in this column could then be "p1_cond1" for the first condition and "p1_cond2" for other, ... . "p1_cond1" and "p1_cond2" would then be listed as estimated parameter in the parameter table.

**Comment by paulflang** [comment]
Thank you very much for the suggestion and clarification, @dweindl . It works now.
