### ISSUE TITLE
xLabel and yLabel are marked as optional in VisualizationTable, but they are not

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#327]
https://github.com/PEtab-dev/PEtab/blob/8b03c8f20c8042c5375adabfe23bab19c3a649b0/petab/visualize/helper_functions.py#L394

https://github.com/PEtab-dev/PEtab/blob/8b03c8f20c8042c5375adabfe23bab19c3a649b0/petab/visualize/helper_functions.py#L396

**Comment by dweindl** [comment]
@erikadudki : is that also addressed in #282?

**Comment by erikadudki** [comment]
yes, also addressed in #282
