### ISSUE TITLE
automatically order xValues according to numerical value

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#330]
[simulation_and_data__cell_cycle_no_M_washout_ridge__AU565__LEE011_Ribociclib__lambda10.0.pdf](https://github.com/PEtab-dev/PEtab/files/4237342/simulation_and_data__cell_cycle_no_M_washout_ridge__AU565__LEE011_Ribociclib__lambda10.0.pdf)

looks odd, I think values also aren't properly aligned

**Comment by FFroehlich** [comment]
[simulation_and_data__cell_cycle_no_M_washout_ridge__AU565__LEE011_Ribociclib__lambda10.0.pdf](https://github.com/PEtab-dev/PEtab/files/4237352/simulation_and_data__cell_cycle_no_M_washout_ridge__AU565__LEE011_Ribociclib__lambda10.0.pdf)

figure I get when manually sorting the dataframe by the specified xValue, looks like there is something screwed up beyond just the ordering of xValues

**Comment by erikadudki** [comment]
automatically ordering of xValues is addressed now in #396, @FFroehlich could you please check if your issue got solved by this? (in develop)

**Comment by FFroehlich** [comment]
changed so many things there by now its difficult to go back to exactly that plotting routine, but fixes look fine
