### ISSUE TITLE
observableId has no effect

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#333]
Not sure if I'm not doing the right thing, but specifying an `observableId` doesn't seem to have an effect to me, everything just always gets aggregated together independent of specified `observableId` or whats in `measurement_df`/`simdata_df`.

[simulation_and_data__cell_cycle_no_M_washout_ridge__AU565__LEE011_Ribociclib__lambda10.0.pdf](https://github.com/PEtab-dev/PEtab/files/4238191/simulation_and_data__cell_cycle_no_M_washout_ridge__AU565__LEE011_Ribociclib__lambda10.0.pdf)

Looking at the code I can't find any place where `OBSERVABLE_ID` is used for subsetting so ...

**Comment by dweindl** [comment]
@MerktSimon or @erikadudki , could you please look into that?

**Comment by plakrisenko** [comment]
Yes, I guess grouping by observableId should be added to get_data_to_plot
