### ISSUE TITLE
Incorrect scale for log10 parameters with estimate=False?

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#342]
Following parameter definition:

parameterId | parameterScale | lowerBound | upperBound | estimate | nominalValue
-- | -- | -- | -- | -- | --
lambda_reg | log10 | 0.001 | 1000.0 | FALSE | 10.0

In

https://github.com/PEtab-dev/PEtab/blob/8b03c8f20c8042c5375adabfe23bab19c3a649b0/petab/parameter_mapping.py#L349

`parameters.scale` rescales the nominal value to logarithmic coordinates and sets it to a numeric value.

https://github.com/PEtab-dev/PEtab/blob/8b03c8f20c8042c5375adabfe23bab19c3a649b0/petab/parameter_mapping.py#L446

only sees a numeric value and claims a linear scale, which means that the value will be passed to the simulator on an incorrect scale, right?

I feel like this is very basic functionality and should be covered by tests.

**Comment by dweindl** [comment]
It's claimed to be tested... will have a look... https://github.com/PEtab-dev/PEtab/blob/8b03c8f20c8042c5375adabfe23bab19c3a649b0/tests/test_parameter_mapping.py#L287

**Comment by dweindl** [comment]
Ah, your case was with `scaled=True`. Seems that was added afterwards without respective tests.

**Comment by dweindl** [comment]
`scaled_parameters` made things a bit more complicated. I suggest changing the current structure, and always generate the parameter (value) mapping together with the scale mapping. Otherwise fixing this would add extra redundancy, and generally one requires both sets of mapping dicts anyways.

**Comment by yannikschaelte** [comment]
agreed!
