### ISSUE TITLE
get_data_to_plot discrepancies

### ISSUE THREAD

**Issue by plakrisenko** [PEtab-dev/PEtab#360]
In commits 
https://github.com/PEtab-dev/PEtab/commit/18317ba4aac8f282a50005fd5118efc796324ff6
https://github.com/PEtab-dev/PEtab/commit/259b641b6d29b4ca06b90c403a944b81db072104?diff=unified
the idea to consider only entries, whose indices ended up in ind_meas, was introduced. Before all m_data was checked, only using m_data.iloc[[ind_meas[0]]] as reference. Right now, it only seems to cause confusion. First of all, it introduced a bug at the line 488 in helper_functions.py:
`        # get intersection of ind_meas and ind_bool_allcond
        ind_intersec = np.intersect1d(ind_meas, ind_bool_allcond)`
It should be
`ind_intersec = [ind_meas[i] for i in ind_bool_allcond]`
as indices in ind_bool_allcond are the induces of elements in ind_meas and not of elements in m_data.
Second,
at the line 456 bool_observable is created, considering all elements in m_data, while at the line 463 only subset of m_data is considered. 

Considering all elements in m_data seems clearer to me. What do you think?

**Comment by MerktSimon** [comment]
Pullrequest #341 will change the ways these indices work quite a lot. I would suggest trying it out with this branch or after merging again and see if the bug still persists.
