### ISSUE TITLE
Clarify whether observables may occur in noiseFormula 

### ISSUE THREAD

**Issue by dweindl** [PEtab-dev/PEtab#368]
... the specs are contradictory there. It says only SBML-entities may show up there, but later an example says observables can be included. If observables can be included, it needs to be clarified whether observableTransformation is to be applied or not.

Opinions?

**Comment by yannikschaelte** [comment]
When allowing observables, the additional question occurs on which scale these should be.
By only allowing states, everything can be achieved by jut copying the observable formula in if observables are needed.

**Comment by JanHasenauer** [comment]
I would suggest to no allow observables which are defined within the observable file. This avoids a lot of headache.
(Assignment rules in the SBML are obviously fine.)

**Comment by yannikschaelte** [comment]
If no-one disagrees, let us then decide that observables are not allowed. This makes implementation easier for the different tools, and does not restrict anything effectively as mentioned above.
