### ISSUE TITLE
petab.sbml.globalize_parameters should modify the kinetic law

### ISSUE THREAD

**Issue by thomassligon** [PEtab-dev/PEtab#376]
`petab.sbml.globalize_parameters` deletes local parameters from each reaction and adds new parameters to the global list of parameters. However, it does not update the kinetic laws in the reactions, do the model is no longer correct (in fact unuseable). This logic should be added to `globalize_parameters`. Unless someone disagrees, I plan to write code for this and submit it via GitHub.

**Comment by dweindl** [comment]
You are right. That came from a different project where it did what it was supposed to do, and somehow ended up here. This function should be removed, it's not really PEtab's business. For you own application: Have a look at libsbml's [SBMLLocalParameterConverter](http://sbml.org/Software/libSBML/5.18.0/docs/cpp-api/class_s_b_m_l_local_parameter_converter.html).

**Comment by thomassligon** [comment]
Assuming that SBMLLocalParameterConverter does what I need, it is definitely the better solution

**Comment by thomassligon** [comment]
The libSBML version is working fine for me. I would close this issue, except that 

> This function should be removed

**Comment by dweindl** [comment]
>  thomassligon closed this 5 days ago 

You did already ;). I marked the function for removal in #381. Fine to leave this closed.
