### ISSUE TITLE
Question: hasOnlySubstanceUnits

### ISSUE THREAD

**Issue by thomassligon** [PEtab-dev/PEtab#384]
I am getting this warning
`2020-03-15 19:22:08.022 - amici.petab_import - WARNING - Ignoring s96 which has only substance units. Conversion not yet implemented.`
236 times. The model contains 342 species, and 236 of them have 
`hasOnlySubstanceUnits="true"`
in SBML. I have no idea where this came from or why, but CellDesigner documents it clearly in the UI.
The SBML documentation states:

> The role of the attribute 'hasOnlySubstanceUnits' is to indicate whether the units of the species, when the species identifier appears in mathematical formulas, are intended to be concentration or amount. The attribute takes on a boolean value. In SBML Level 3, the attribute has no default value and must always be set in a model; in SBML Level 2, it has a default value of false.

It might have a meaning, such as setting genes to amount and proteins to concentration, but the model seems to be more a matter of chance.

Do we have any recommendations for this?

**Comment by dweindl** [comment]
Hi Tom, this issue is rather about AMICI, not PEtab itself. As in your case, there doesn't seem to be any specific reason for hasOnlySubstanceUnits=true, you could as well just change that to false.

**Comment by thomassligon** [comment]
Thanks. I'll ask the question on AMICI.
