### ISSUE TITLE
visualization of dose response data

### ISSUE THREAD

**Issue by elbaraim** [PEtab-dev/PEtab#393]
I get some messed up visualization when executing the following code on the 
`Benchmark-Models-PEtab/Benchmark-Models`
on the branch `model_Casaletto_PNAS2019`

``` python
from petab.visualize import plot_data_and_simulation
import matplotlib.pyplot as plt

model_name = "Casaletto_PNAS2019"

data_file_path = "./"+model_name+"/measurementData_"+model_name+".tsv"
condition_file_path = "./"+model_name+"/experimentalCondition_"+model_name+".tsv"
visualization_file_path = "./"+model_name+"/visualizationSpecification_"+model_name+".tsv"
simulation_file_path = "./"+model_name+"/simulatedData_"+model_name+".tsv"

# function to call, to plot data and simulations
ax = plot_data_and_simulation(data_file_path,
                              condition_file_path,
                              visualization_file_path)
plt.show()
```
![Screenshot from 2020-03-19 19-26-46](https://user-images.githubusercontent.com/10628853/77147792-6758e200-6a8e-11ea-9c2c-85393cfc2e50.png)

Maybe something with the ordering of the data goes wrong?
Thanks for the help :smile:

**Comment by MerktSimon** [comment]
see also #207 and #330

**Comment by erikadudki** [comment]
one issue I found regarding this dataset was, that reading in the unique conditionIDs (e.g. model1_data**1**, model1_data**2**,...,model1_data**10**,..) sorts the conditionIDs automatically with: model1_data**1**,model1_data**10**, model1_data**11**, model1_data**2**,...
I would fix that, while trying to reserve the ordering from the table, but this still does not fix the issue, if Xvalues are unordered.

**Comment by elbaraim** [comment]
> one issue I found regarding this dataset was, that reading in the unique conditionIDs (e.g. model1_data**1**, model1_data**2**,...,model1_data**10**,..) sorts the conditionIDs automatically with: model1_data**1**,model1_data**10**, model1_data**11**, model1_data**2**,...
> I would fix that, while trying to reserve the ordering from the table, but this still does not fix the issue, if Xvalues are unordered.

automatic sorting of the x-values would fix this even if in the table are not ordered ;) #207
