### ISSUE TITLE
pandas FutureWarning in petablint

### ISSUE THREAD

**Issue by thomassligon** [PEtab-dev/PEtab#394]
After upgrading petab from 0.1.1 to 0.1.5, and, as a result, upgrading pandas from 0.25.3 to 1.0.3, I get a warning in petablint

```
C:\data\Tom\Research\Asthma\python>petablint -y configuration.yaml
c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  res_values = method(rvalues)
```

**Comment by elbaraim** [comment]
> After upgrading petab from 0.1.1 to 0.1.5, and, as a result, upgrading pandas from 0.25.3 to 1.0.3, I get a warning in petablint
> 
> ```
> C:\data\Tom\Research\Asthma\python>petablint -y configuration.yaml
> c:\program files (x86)\microsoft visual studio\shared\python37_64\lib\site-packages\pandas\core\ops\array_ops.py:253: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
>   res_values = method(rvalues)
> ```

same for me
