### ISSUE TITLE
yOffset does not have an effect

### ISSUE THREAD

**Issue by elbaraim** [PEtab-dev/PEtab#413]
I am changing the value in the yOffset column and it does not have any effect in the visualization while xOffset does.
- Any clue? Is this not yet implemented by chance?

Thanks!

**Comment by yannikschaelte** [comment]
it does not appear in the code, so it would seem to be not implemented.

**Comment by dweindl** [comment]
> it does not appear in the code, so it would seem to be not implemented.

I think that was already discussed somewhere. Didn't find it. Maybe it was mattermost.

**Comment by MerktSimon** [comment]
the commit refers to yValue offset, sorry for typo
