### ISSUE TITLE
objectivePriorType vs. priorType

### ISSUE THREAD

**Issue by paulflang** [PEtab-dev/PEtab#448]
The columns in the [parameter table format documentation](https://petab.readthedocs.io/en/stable/documentation_data_format.html#parameter-table) contain `priorType` and `priorParameters`, whereas the detailed field description contains `initializationPriorType`, `initializationPriorParameter`, `objectivePriorType` and `objectivePriorParameter`. I assume this feature is still evolving/being developed, but is it already clear what column labels should be used?

**Comment by dweindl** [comment]
Hi @paulflang , it seems the overview table has not been updated. The "detailed description" is correct. Needs to be fixed, thanks for reporting.
