### ISSUE TITLE
PEtab's petablint validator doesn't seem to actually recognize .sbml files?

### ISSUE THREAD

**Issue by VitaminBrad** [PEtab-dev/PEtab#456]
Gedit could find it and the validator appears to be working just fine on the provided .yaml example https://i.imgur.com/aUPqZJe.png

Funnily enough, the cat command appears to also say "no such file or directory on my machine, but then proceeds to work just fine: https://i.imgur.com/SCNuZhf.png

I am on a Fedora machine in an Anaconda environment.

Best,

**Comment by dweindl** [comment]
Hi @VitaminBrad, I think you just missed putting a  `/` in your path (`..Models/` vs. `../Models`).

**Comment by dweindl** [comment]
Also note that  `petablint -y` expects a YAML file, not an SBML file. If you want to check the SBML file alone, you can use `petablint -s $yourSbmlFile`. See `petablint -h` for more usage information.

**Comment by VitaminBrad** [comment]
> Hi @VitaminBrad, I think you just missed putting a `/` in your path (`..Models/` vs. `../Models/`).

How embaressing... Long day alone at the (home)office - my apologies. I'll try to double-check before asking anything again in the future...



> Also note that `petablint -y` expects a YAML file, not an SBML file. If you want to check the SBML file alone, you can use `petablint -s $yourSbmlFile`. See `petablint -h` for more usage information.

Great. Thanks, @dweindl.
