### ISSUE TITLE
Separate repositories for PEtab format specification and library 

### ISSUE THREAD

**Issue by dweindl** [PEtab-dev/PEtab#476]
I'd suggest to split this repository and have one dedicated to the PEtab format specification and one to the python library. This makes it easier to keep track of specification changes and is more convenient for anybody not interested in the Python library.

Suggesting PEtab-dev/PEtab for specs and  PEtab-dev/libpetab-python for the library.

Any opinions?

**Comment by yannikschaelte** [comment]
Sounds reasonable. Does not change any relevant existing external links as the format documentation remains with the PEtab module.

I would keep the name "petab" for the python/pypi package.

**Comment by dweindl** [comment]
If nobody is opposed, I'd just create a clone of this repo at `petab-dev/libpetab-python` without filtering the history, and then remove the no longer needed files in both repos. That would save quite some pain...
