### ISSUE TITLE
observable table vs observables table 

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#525]
Documentation is inconsistent in using  "observables table" and "observable table" https://petab.readthedocs.io/en/latest/documentation_data_format.html#observables-table

Code seems to be pretty consistent with "observable_df", so maybe we should stick with that?

**Comment by dweindl** [comment]
Agreed, would be good to use consistent terminology. No strong preference for either "observables table" or "observable table".
