### ISSUE TITLE
Proposed new column in measurementData.tsv: datapointId

### ISSUE THREAD

**Issue by dlill** [PEtab-dev/PEtab#531]
**Which problem would you like to address? Please describe.**
A unique identifier for each data point (i.e. row) in measurementData. 
This way, one can 
* Document easily if one excluded certain data points
* Discuss with collaborators about specific data points which raised questions
* Have an additional discerning factor when merging/using multiple measurementData files
* Useful in visualization. Annotating plots, one can quickly pin point problems in the data set

**Describe the solution you would like**
Add a new optional character column called `datapointId` in measurementData.
This can be coded manually by the user. It could simply be the respective row number, but it can also be a string like `datasetId_rownumber`.
Each entry *must* be unique

**Describe alternatives you have considered**
Location: None. This is the only place where such an addition makes sense.
Structure: One could restrict the format of datapointId more tightly

**Additional context**
I guess it won't break much legacy code

**Comment by dweindl** [comment]
Hi @dlill, thanks for your suggestion. I see the potential applications. However, as long as there is nothing within PEtab that uses this information directly, I would not make it part of the format specification.  But maybe there are other opinions... 
Nevertheless, it's already possible to add arbitrary additional columns in the measurement files.

**Comment by dlill** [comment]
Okay, then I read the documentation not carefully enough - I already thought that datasetId and replicateId were part of the standard, but now I see that they also rather belong to the visualization functionality. Could you include a column ... for additional non-standard columns in the documentation to emphasize that other columns may be added?

**Comment by dweindl** [comment]
https://petab.readthedocs.io/en/stable/documentation_data_format.html#measurement-table already states:

> Additional (non-standard) columns may be added.

**Comment by dlill** [comment]
Sure, it's just for the emphasis - this detail is easily missed, because the eye is naturally guided to the column description.
