### ISSUE TITLE
Allow using observables in noiseFormula

### ISSUE THREAD

**Issue by dweindl** [PEtab-dev/PEtab#543]
Currently it is not allowed to use observable IDs in `noiseFormula` in the observables table (#368). It would be great to allow that.

This would convenient for specifying relative errors. Although the `observableFormula` could be copied to the `noiseFormula`, it would be more readable and less error prone if one could simply use the respective `observableId`.

Also, some tools do not support state variables, but only observables in noise models, so this would be convenient there too.

Opinions?

**Comment by eraimundez** [comment]
There seems to be something around that maybe could be used / adapted?
https://help.juliahub.com/pumasqsp/dev/example/petabimport/ (see first green box when scrolling down)

**Comment by dweindl** [comment]
> There seems to be something around that maybe could be used / adapted? https://help.juliahub.com/pumasqsp/dev/example/petabimport/ (see first green box when scrolling down)

This doesn't really require much adaptation. It's mostly about making a decision whether we want to allow that. (I think we should.) 
Thanks for the reminder, I'll bring that up again in the next PEtab editor meeting (ping @PEtab-dev/petab-editors).
