### ISSUE TITLE
Bounds documentation needs clairification

### ISSUE THREAD

**Issue by shoepfl** [PEtab-dev/PEtab#546]
Hey there,

i am confused by the current documentation for the parameter bounds of the PEtab files. The current statemet in the docs is that the bounds "Must be provided in linear space, independent of parameterScale."

From this I would expect that also my given linear bounds are respected, but they are subsequently converted to the parameterScale and therefore the bound i give in linear space is not respected but its transformation to the other scale.

Maybe one sentence for the clairification would be sufficient here, that states one has to be careful here that the given linear bound is not the one that is respected later (but its transformation to the parameterScale).

**Comment by dweindl** [comment]
Hi @shoepfl, would the proposed changes in https://github.com/PEtab-dev/PEtab/pull/547/files clarify things for you?

**Comment by shoepfl** [comment]
Thanks @dweindl looks perfekt for me.
