### ISSUE TITLE
No reference to paper in repository

### ISSUE THREAD

**Issue by FFroehlich** [PEtab-dev/PEtab#572]
**Which problem would you like to address? Please describe.**
I can't find a link to the PEtab paper on the main page of the repo.

**Describe the solution you would like**
There should be a link/reference to https://doi.org/10.1371/journal.pcbi.1008646 somewhere, ideally with a [CITATION](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) file.

**Describe alternatives you have considered**
Search for it using google

**Comment by dweindl** [comment]
:+1: for CITATION.cff
