### ISSUE TITLE
Use absolute paths in README for pypi

### ISSUE THREAD

**Issue by yannikschaelte** [PEtab-dev/PEtab#89]
Since we use the README as the page shown in pypi as well (https://pypi.org/project/petab/#description), we probably should only use absolute path links, because otherwise those won't work there. Currently affects the link to the doc.

**Comment by dweindl** [comment]
Hmm... then it won't work offline anymore. Ideally we'd replace them in setup.py where it is loaded into the package description

**Comment by dweindl** [comment]
Fixed.
